### ISSUE TITLE
Unable to build on fresh clone

### ISSUE THREAD

**Issue by sarath-crypto** [astoeckel/http_audio_server#1]
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for module 'opus'
--   Found opus, version 1.1.2
CMake Error at CMakeLists.txt:29 (add_subdirectory):
  The source directory
    /home/sarath/Work/http_audio_server/lib/libwebm
  does not contain a CMakeLists.txt file.
-- Configuring incomplete, errors occurred!
See also "/home/sarath/Work/http_audio_server/build/CMakeFiles/CMakeOutput.log".

**Comment by astoeckel** [comment]
You most likely forgot to include the `--recursive` flag when cloning the repository. Thus `libwebm` was not checked out.

Simply run
```
git submodule init
git submodule update
```
in the root repository directory. This will download the missing libwebm dependency. Let me know if this works for you.

**Comment by sarath-crypto** [comment]
On adding --recursive it worked the cmake advanced.
