### ISSUE TITLE
git fresh clone failed cmakelists.txt:75 mkvmuxer on cmake

### ISSUE THREAD

**Issue by sarath-crypto** [astoeckel/http_audio_server#2]
Checking CXX compiler flag support for: -Wshorten-64-to-32
-- Performing Test CXX_FLAG_SUPPORTED
-- Performing Test CXX_FLAG_SUPPORTED - Failed
CMake Error at CMakeLists.txt:75 (target_link_libraries):
  Target "mkvmuxer" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.

**Comment by astoeckel** [comment]
I've comited a new version that links to `webm` instead of `mkvmuxer`, which seems to be the correct way to do things with the new version of libwebm if pushed yesterday (though I did work for me; maybe this is a difference between cmake versions).

Can you try again?

**Comment by sarath-crypto** [comment]
Yes , it is compiling now. Thank you very much.
