### ISSUE TITLE
Not working for raspibian

### ISSUE THREAD

**Issue by sarath-crypto** [astoeckel/http_audio_server#3]
Hi ,
It is working fine between two machines in same LAN . My setup is
1) ubuntu (server)- wifi tethering -ubuntu (client) - working fine.
2) raspberry Pi2 (raspibian)10.10.10.1 (server)-Ethernet -10.10.10.2 ubuntu(client) - not working. Is it something to do with security context of firefox? 
Thanks in advance,
Sarath

**Comment by astoeckel** [comment]
Please clarify what you mean by not working. Are there any error messages? Does the web interface load on the remote machine? Did you install ffmpeg and ffprobe on your Raspbian device? I don't see any reason why there should be a difference between Ubuntu and Raspbian.

**Comment by sarath-crypto** [comment]
Web page is loaded , able to add play list and mp3 source file info is displayed in web page on clicking "play" button, but sound is not coming neither the sound enabled symbol not showing in browser tab (firefox) also. If we can  make work in raspibian there can more users for this project.ffmpeg and ffprobe is installed already.

**Comment by astoeckel** [comment]
Weird. This indicates that ffprobe is working. Are there any error messages in the developer console in Firefox on the client? What does the log of the server application say?

**Comment by sarath-crypto** [comment]
GEThttp://10.10.10.1:4851/favicon.ico
Opening stream... 

Above is the console output for firefox.

Application log says
"advance"

**Comment by astoeckel** [comment]
Can you try a file with an audio codec different than MP3 (preferably a free codec such as flac, wav or ogg vorbis)? Maybe Raspbian/Debian still doesn't ship with an MP3 decoder. If free codecs work, then you have to manually compile ffmpeg for raspbian.

If it also doesn't work with a free audio codec, then please add some debug code to `http_audio_server/main.cpp` line 98. Replace the following code
```c++
// Read the data
if (dec->read(n_bytes, m_buf)) {
    const size_t n_samples_read = m_buf.size() / sizeof(float) / 2;
```
with something along the line of
```c++
std::cout << "Attempting to read from the decoder" << std::endl;
if (dec->read(n_bytes, m_buf)) {
    const size_t n_samples_read = m_buf.size() / sizeof(float) / 2;
    std::cout << "Read " << n_samples_read << " samples from the decoder." << std::endl;
```
Compare the output between your Ubuntu machine and the Raspbian machine.

**Comment by sarath-crypto** [comment]
1) Tried with wav file on raspibian - not working, same for mp3 also.
2)Added the debug code for both ubuntu and raspibian, both are identical except the working one(ubuntu) logs are advancing  but for raspibian it is strucked after couple of log outputs. Below is raspibian output.

rdf@ears:~/http_audio_server/build $ ./http_audio_server
2021-01-01 10:58:14 [server] info: Serving HTTP at 0.0.0.0:4851, press CTRL+C to exit
GET /
GET /favicon.ico
POST /stream/create
POST /stream/YPYVBxIGEEGOPDVq/append
POST /stream/YPYVBxIGEEGOPDVq/advance
Attempting to read from the decoder
Read 240000 samples from the decoder.
POST /stream/YPYVBxIGEEGOPDVq/advance
Attempting to read from the decoder
Read 240000 samples from the decoder.

**Comment by astoeckel** [comment]
I just tried running the program on raspbian myself and I can reproduce your issue. I have no idea what is going wrong, but I will let you know once I have figured it out.

**Comment by sarath-crypto** [comment]
Dear Andreas , Thank you very much, let me also try to read something on these topics so that I can also try attacking this issue in parallel with best of my knowledge.

**Comment by astoeckel** [comment]
Found it; there is an integer overflow in line 165 of `encoder.cpp` on 32 bit systems. The variables `m_rate` and `m_granule` should be `uint64_t` and not `size_t`. I've pushed a fix.

Edit: I just pushed another commit; don't know whether that last change was necessary (though it shouldn't hurt), the compile times on my Raspberry Pi 1 are really long, making testing a little cumbersome...

**Comment by sarath-crypto** [comment]
Impressive bug and impressive solution when we move from 64 to 32 bit word length machines. Thank you Andreas, now I am able to listen to music from raspibian. I cloned a fresh one, compiled on raspibian  (pi2) , now it is working fine.

**Comment by sarath-crypto** [comment]
Impressive bug and impressive solution when we move from 64 to 32 bit word length machines. Thank you Andreas, now I am able to listen to music from raspibian. I cloned a fresh one, compiled on raspibian  (pi2) , now it is working fine.
